[build-system]
requires = ['hatch-vcs>=0.3.0', 'hatchling>=1.24.2,<1.25']
build-backend = 'hatchling.build'


[project]
name = 'cogkit'
dynamic = ['version']
description = ''
readme = 'README.md'
requires-python = '>=3.10'
license = 'Apache2.0'
keywords = []
authors = [{ name = 'ZhipuAI', email = 'opensource@zhipuai.cn' }]
classifiers = [
  'Development Status :: 4 - Beta',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: Implementation :: CPython',
  'Programming Language :: Python :: Implementation :: PyPy',
  'Programming Language :: Python',
]
dependencies = [
  "accelerate~=1.3",
  "click~=8.1",
  "datasets~=3.2",
  "deepspeed~=0.16.3",
  "diffusers@git+https://github.com/huggingface/diffusers.git",
  "imageio-ffmpeg~=0.6.0",
  "imageio~=2.37",
  "peft~=0.14.0",
  "pydantic~=2.10",
  "sentencepiece~=0.2.0",
  "transformers~=4.49",
  "wandb~=0.19.6",
]

[project.optional-dependencies]
torch = ["numpy", "torch", "torchvision"]
video = ["decord~=0.6.0", "opencv-python-headless~=4.11"]

[project.scripts]
cogkit = "cogkit.cli:cli"

[tool.hatch.version]
source = 'vcs'


[tool.hatch.version.raw-options]
version_scheme = 'python-simplified-semver'
local_scheme = 'no-local-version'


[tool.hatch.build.hooks.vcs]
version-file = 'src/cogkit/_version.py'


[tool.hatch.metadata]
allow-direct-references = true


[tool.ruff]
exclude = ['.git', '.mypy_cache', '.ruff_cache', '.venv', 'dist']
target-version = 'py310'
line-length = 100

[tool.ruff.format]
line-ending = 'lf'
quote-style = 'preserve'

[tool.ruff.lint]
select = ["E", "W"]
ignore = [
  "E501",
  "E999",
  "EXE001",
  "F401",
  "F403",
  "F841",
  "TID252",
  "UP009",
  "W293",
]
